CREATE USER 
'tienda2627'@'localhost' 
IDENTIFIED  BY 'TAME123$';

GRANT USAGE ON *.* TO 'tienda2627'@'localhost';

ALTER USER 'tienda2627'@'localhost' 
REQUIRE NONE 
WITH MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 
MAX_UPDATES_PER_HOUR 0 
MAX_USER_CONNECTIONS 0;


GRANT ALL PRIVILEGES ON tienda2627.* 
TO 'tienda2627'@'localhost';

FLUSH PRIVILEGES;